### ISSUE TITLE
Add compatibility with netresearch/jsonmapper ^2.0

### ISSUE THREAD

**Issue by a-menshchikov** [felixfbecker/php-advanced-json-rpc#38]
This package required for static analyzer phan, and now we cannot use it in projects, where have using netresearch/jsonmapper ^2.0 (for example lesstif/php-jira-rest-client have such dependency).

**Comment by felixfbecker** [comment]
PR welcome.

**Comment by a-menshchikov** [comment]
@felixfbecker done.
