### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-advanced-json-rpc#46]
Travis is pretty unreliable now so would like to convert to GitHub actions. Example: https://github.com/xdebug/vscode-php-debug/blob/main/.github/workflows/build.yml

**Comment by szepeviktor** [comment]
> Travis is pretty ...

Travis is a mature product. GHA is the hyped one.
But it takes ~1 day to dig deep!! (which I've done)

**Comment by felixfbecker** [comment]
Ever since Travis went bankrupt, got bought and switched to credit-based pricing for open source, I've seen builds being stuck and not scheduled a lot. I don't want to have to deal with that. GitHub actions, hyped or not, works flawlessly.

See https://news.ycombinator.com/item?id=25338983 for more info
